DROP TRIGGER IF EXISTS supplier_claim_evidence_preparation_freeze ON supplier_claim_evidence_links;
DROP FUNCTION IF EXISTS prevent_evidence_link_after_submission_preparation();
DROP TRIGGER IF EXISTS supplier_claim_evidence_no_delete ON supplier_claim_evidence_links;
DROP TRIGGER IF EXISTS supplier_claim_evidence_no_update ON supplier_claim_evidence_links;
DROP TRIGGER IF EXISTS supplier_claim_events_no_delete ON supplier_claim_events;
DROP TRIGGER IF EXISTS supplier_claim_events_no_update ON supplier_claim_events;
DROP FUNCTION IF EXISTS prevent_supplier_claim_history_mutation();
DROP TRIGGER IF EXISTS supplier_claim_submission_identity_immutable ON supplier_claim_submission_operations;
DROP TRIGGER IF EXISTS supplier_claim_submission_transition_valid ON supplier_claim_submission_operations;
DROP FUNCTION IF EXISTS validate_supplier_claim_submission_transition();
DROP FUNCTION IF EXISTS prevent_supplier_claim_submission_identity_change();
DROP TRIGGER IF EXISTS supplier_claim_submission_exact_identity ON supplier_claim_submission_operations;
DROP FUNCTION IF EXISTS validate_supplier_claim_submission_identity();
DROP TRIGGER IF EXISTS supplier_claim_evidence_exact_order ON supplier_claim_evidence_links;
DROP FUNCTION IF EXISTS validate_supplier_claim_evidence_link();
DROP TRIGGER IF EXISTS supplier_claims_identity_immutable ON supplier_claims;
DROP FUNCTION IF EXISTS prevent_supplier_claim_identity_change();
DROP TRIGGER IF EXISTS supplier_claims_exact_identity ON supplier_claims;
DROP FUNCTION IF EXISTS validate_supplier_claim_identity();
DROP INDEX IF EXISTS supplier_claim_events_claim_idx;
DROP TABLE IF EXISTS supplier_claim_events;
DROP INDEX IF EXISTS supplier_claim_evidence_claim_idx;
DROP TABLE IF EXISTS supplier_claim_evidence_links;
DROP INDEX IF EXISTS supplier_claim_submission_status_idx;
DROP TABLE IF EXISTS supplier_claim_submission_operations;
DROP INDEX IF EXISTS supplier_claims_order_updated_idx;
DROP INDEX IF EXISTS supplier_claims_active_issue_idx;
DROP INDEX IF EXISTS supplier_claims_idempotency_idx;
DROP TABLE IF EXISTS supplier_claims;
